version: "3.7"
services:
    ws:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3050:80"
        environment:
            - CSP_CONNECT_SRC=*
        volumes:
            - /home/paul/Documents/pektin/pektin-ui/build/:/public/
            - ./config.yml:/config.yml
