version: "3.7"
services:
    ws-prod:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3050:80"
        environment:
            - CSP_CONNECT_SRC=*
        volumes:
            - /home/paul/Documents/wirnharter3/build/:/public/
